name: datk
description: Steno Type

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_messaging: ^10.0.3 #6.0.13
  google_sign_in: ^5.0.4 #4.0.7
  shared_preferences: ^2.0.6 #0.5.3+4
  url_launcher: ^6.0.9
  fluttertoast: ^8.0.7
  cached_network_image: ^3.0.0
  material_design_icons_flutter: ^4.0.5345
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0  #0.14.0+5
  cloud_firestore: ^2.3.0 #^0.12.9+5
  image_picker: ^0.8.1+4 #0.6.1+8
  firebase_storage: ^9.0.0 #3.0.6
  intl: ^0.17.0 #0.15.7
  flutter_local_notifications: ^6.0.0 #1.4.0
  photo_view: ^0.11.1 #0.5.0
  percent_indicator: "^2.1.7+2"
  flutter_rating_bar: ^4.0.0
  device_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - lib/image/steno_keyboard.jpg
    - lib/image/HOC.png
    - lib/image/KIEM_TRA.jpg
    - lib/image/THI_DAU.png
    - lib/image/selection_background.JPG
    - lib/image/hoc_go_phim.png
    - lib/image/hoc_go_tu.png
    - lib/image/hoc_go_am.png
    - lib/image/hoc_go_tu_do.jpg
    - lib/image/hoc_go_so.jpg
    - lib/image/hoc_go_cau.png
    - lib/image/kiem_tra_do_chinh_xac.png
    - lib/image/kiem_tra_do_kho.png
    - lib/image/kiem_tra_gioi_han_thoi_gian.png
    - lib/image/kiem_tra_toc_do.png
    - lib/image/windows10.png
    - lib/image/xep_hang_background.JPG
    - lib/image/note_5.png
    - lib/image/redmi_7.png